In [1]:
import numpy as np


mat = np.mat("1 2 3;1 3 4;3 2 1")

# Original matrix
print(mat)
print("")
evalue, evect = np.linalg.eig(mat)

# Eigenvalues of the said matrix"
print(evalue)
print("")

# Eigenvectors of the said matrix
print(evect)

# NOTE that the eigenvectors are the COLUMNS of the evect matrix.
# In the example below the vector (-0.42932,0.7945835,-0.42932) is the eigenvector corresponding
# to the eigenvalue 0.29843788

[[1 2 3]
 [1 3 4]
 [3 2 1]]

[ 6.70156212  0.29843788 -2.        ]

[[-0.5113361  -0.42932334 -0.40482045]
 [-0.69070311  0.7945835  -0.52048344]
 [-0.5113361  -0.42932334  0.75180941]]


In [2]:
evect[:,0]

matrix([[-0.5113361 ],
        [-0.69070311],
        [-0.5113361 ]])

In [3]:
sorted_indices = np.argsort(evalue)
sorted_eigenvalues = evalue[sorted_indices]
sorted_eigenvectors = evect[:,sorted_indices]

In [4]:
sorted_eigenvalues

array([-2.        ,  0.29843788,  6.70156212])

In [5]:
sorted_eigenvectors

matrix([[-0.40482045, -0.42932334, -0.5113361 ],
        [-0.52048344,  0.7945835 , -0.69070311],
        [ 0.75180941, -0.42932334, -0.5113361 ]])